### ISSUE TITLE
Lock icon doesn’t work properly 

### ISSUE THREAD

**Issue by anrqkdrnl** [SniperGER/ProudLock2#1]
It doesn’t change when unlocked

**Comment by zyan910** [comment]
Yeah same issue here, but apparently if you play around with the cover sheet, it shows the unlocked icon for a second or two

i6. 12.1.2

**Comment by SniperGER** [comment]
At this point of development, I'd call that "intended", as weird as it may sound.

I have honestly not done enough research on how this thing works on iOS 12 yet, so this may take a while to be fixed.

**Comment by NickKrahn** [comment]
Same issue for me (i6s+ iOS 12.1.1) I hope this gets fixed soon. I know how long things like this could take if you have to figure it out, so I'm not rushing you, but keep up the great work
