### ISSUE TITLE
Not working on iOS 13.5

### ISSUE THREAD

**Issue by SyedMuhammadAhmad** [SniperGER/ProudLock2#12]
ProudLock XR isn’t working on iOS 13.5.  Padlock doesn’t show on lock screen.  Waiting for it’s new update

**Comment by SniperGER** [comment]
What device are you using? The internal version is working just fine on my iPad Pro 10.5" (which changed absolutely nothing regarding the padlock, only fixing Rest to Unlock)

**Comment by SyedMuhammadAhmad** [comment]
iPhone SE(first generation) on iOS 13.5 
Padlock isn’t showing on lock screen.

**Comment by SyedMuhammadAhmad** [comment]
On iOS 12 last year. ProudLock XR was working perfectly on my iPhone SE(first generation) but now on iOS 13.5 Padlock isn’t on lock screen.

**Comment by SniperGER** [comment]
I guess it's because iPads already include the required assets by default, and the class that ProudLock hooks to redirect to assets included by the tweak isn't used anymore on iOS 13.

I'll see if I can quickly fix it.

**Comment by SniperGER** [comment]
Fixed with 15aecf9. Update will be released as soon as I've got a working iOS 13.5 SDK with private frameworks.

**Comment by SyedMuhammadAhmad** [comment]
Thanks a lot. I’ll be waiting for the update

**Comment by SniperGER** [comment]
Update has been released on https://repo.festival.tf, so I'm going to close this for now. Feel free to reopen if it doesn't work for you.

**Comment by SyedMuhammadAhmad** [comment]
![678BD16C-0EFA-4031-A21A-5F26C3DD4FB5](https://user-images.githubusercontent.com/49991627/85010157-f7372680-b178-11ea-9357-1d3961da4df7.png)

In Beta 0.3-2 Padlock isn’t showing on lock screen. As it was showing in 0.3-1

There was also one bug that when I lock phone after changing the wallpaper the padlock remains unlock while phone was locked.
