### ISSUE TITLE
Replaces the lock icon in silent mode hud switch

### ISSUE THREAD

**Issue by Xclaveria23** [SniperGER/ProudLock2#13]
It replaces the silent mode switch lock hud with the lockscreen lock of iphone x

![D0214E19-0370-4E2D-B16F-BDC0E29F9432](https://user-images.githubusercontent.com/67096263/84996892-74b26500-b180-11ea-9da7-425de0bee976.png)

**Comment by SniperGER** [comment]
Fixed with 0.3-2. Thanks for the info!

**Comment by SyedMuhammadAhmad** [comment]
![4B81CECE-D11F-4787-A61E-0E845D99EF98](https://user-images.githubusercontent.com/49991627/85009676-47fa4f80-b178-11ea-92fc-ca17cefb4a2c.png)

In Beta 0.3-2 Padlock isn’t showing on lock screen. As it was showing in 0.3-1

There was also one bug that when I lock phone after changing the wallpaper the padlock remains unlock while phone was locked.

**Comment by SyedMuhammadAhmad** [comment]
![AE911FFF-76B3-4B88-BC9A-2290E96360BC](https://user-images.githubusercontent.com/49991627/85024334-60c22f80-b18f-11ea-911a-210983cf35ca.png)


Thanks alo
![8074281D-928A-420A-8DB6-232840590AF5](https://user-images.githubusercontent.com/49991627/85024350-66b81080-b18f-11ea-83c6-65b8ecd7834d.png)


Thanks a lot. Padlock is now showing on lock screen.
